#server:
#  port: ${PORT:8081}   # Render এ PORT env var সেট করে, তাই ${PORT} ব্যবহার করতে হবে
#
#eureka:
#  client:
#    service-url:
#      defaultZone: https://your-discovery-server.onrender.com/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#
#spring:
#  datasource:
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    driverClassName: org.postgresql.Driver
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
