server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false   # Server নিজেই register হয় না
    fetch-registry: true           # Registry fetch করতে পারে (for peer servers)
  server:
    wait-time-in-ms-when-sync-empty: 0  # auto-refresh for UI faster
