server:
  port: 8083   # render বা production এও একই রাখতে পারো

spring:
  datasource:
    url: jdbc:postgresql://<your-db-host>:5432/orderdb
    driver-class-name: org.postgresql.Driver
    username: <db-username>
    password: <db-password>

spring.jpa:
  hibernate.ddl-auto: update
  show-sql: false

eureka:
  client:
    service-url:
      defaultZone: https://<your-discovery-server-url>/eureka
