server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/robiulhossain10/Spring-Microservices
          default-label: master
          search-paths: config-repo
          clone-on-start: true
