server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          # শুধু repo এর মূল URL দাও
          uri: https://github.com/robiulhossain10/Spring-Microservices
          default-label: master   # branch নাম master হলে master দাও, না হলে main
          search-paths: config-repo  # repo এর ভেতরে যে ফোল্ডারে configs আছে
